### ISSUE TITLE
Add newline or <br />? if not empty

### ISSUE THREAD

**Issue by theopensourcerer** [Skrol29/tinybutstrong#17]
Forgive if this is dumb question - I couldn't find anything obvious in the manual...

Suppose I have several fields which form an Address. I would like to add a newline to each field, only if they are not empty.

i.e.

[onload.street1;ope=add:\n][onload.street2;ope=add:\n][onload.city;ope=add:\n][etc...

Is something like this possible?

**Comment by roxblnfk** [comment]
Have you watched this section? https://www.tinybutstrong.com/manual.php#html_conditional_section

**Comment by theopensourcerer** [comment]
@roxblnfk Thanks - I have no idea how I missed that!!!

**Comment by Skrol29** [comment]
I would suggest
   [onload.street1;magnet=br;mtype=m*] for <br>
or
   [onload.street1;magnet=_] for text new line

**Comment by theopensourcerer** [comment]
@Skrol29 Thanks for responding. 

I saw mention of the block=_ in the documentation but didn't realise I could apply it to fields. 

Unfortunately I just tried either method without success.

Using `[onload.street1;magnet=_]` the template is created, but the resulting odt file couldn't be opened. 
![Screenshot from 2020-04-05 10-09-17](https://user-images.githubusercontent.com/3414988/78470988-96758180-7725-11ea-90e6-5ee0108fa9a0.png)


And with  `<br>[onload.street1;magnet=br;mtype=m*]` the br is just being printed as-is in the resulting odt template and not intepreted...

![Screenshot from 2020-04-05 10-06-46](https://user-images.githubusercontent.com/3414988/78470946-3252bd80-7725-11ea-9769-824dde602c6e.png)

**Comment by theopensourcerer** [comment]
Awesome - I've worked it out. This works for OpenTBS odt files...

`[onload.bill_street;magnet=text:line-break;mtype=*m]followed by a soft line-break. See screenshot:
![Screenshot from 2020-04-05 10-57-02](https://user-images.githubusercontent.com/3414988/78471861-45b55700-772c-11ea-85cc-bcb561fee928.png)

**Comment by Skrol29** [comment]
« magnet=_ » is for textual line break, like "/n"
No good for XML contents.
