### ISSUE TITLE
Parameter to detect if field exists?

### ISSUE THREAD

**Issue by bodywatch-it** [Skrol29/tinybutstrong#18]
I'm trying to apply a block with data that may or may not have a given field set. I can use a conditional to display things or not with `when` , but this causes an error (naturally) when it's evaluating the conditional.
I can apply `noerr` at the template level (I think?), but I'd rather it be done at the block level (or possibly field level).
Is this possible, or should I try making a `empty_if_missing()` function at the passed-in-class object thing?

**Comment by Skrol29** [comment]
Yes is it possible. See parameter `noerr` for fields.

https://www.tinybutstrong.com/manual.php#html_field_prm_noerr

**Comment by bodywatch-it** [comment]
I must be doing something wrong then? 😕 

    [data;noerr=true;block=landmark;when [data.AS_FPTXYZ] != '']

Is this out of order or otherwise incorrect?

**Comment by Skrol29** [comment]
[data;block=landmark;when '[data.AS_FPTXYZ;noerr]' != '']

or 

[data.AS_FPTXYZ;noerr;block=landmark;magnet=landmark]

**Comment by bodywatch-it** [comment]
Awesome, thanks!
