### ISSUE TITLE
TBS library not working with latest pptx versions

### ISSUE THREAD

**Issue by ashifaliclientpoint** [Skrol29/tinybutstrong#30]
hi
We are using TBS library to create a new pptx file after find and replace tags from master pptx file.
It is working fine. But same code is not working with latest pptx files. Can you please help me to fix this issue. 
I am using below set of code. Please review and please let me know if i am doing something wrong.Also sharing file.

require_once ("opentbs/tbs_class.php");
require_once ("opentbs/tbs_plugin_opentbs.php");
$pptx = new clsTinyButStrong (); // new instance of TBS
$pptx->Plugin ( TBS_INSTALL, OPENTBS_PLUGIN ); // load the OpenTBS plugin
$pptx->LoadTemplate($fileNameIn, OPENTBS_ALREADY_UTF8);
$pptx->PlugIn(OPENTBS_SELECT_SLIDE, 1);
$pptx->VarRef["Rep_Name"] = $templateDataArray["Rep_Name"];
$pptx->PlugIn(OPENTBS_SELECT_SLIDE, 1);
$pptx->VarRef["Rep_Title"] = $templateDataArray["Rep_Title"];
$pptx->PlugIn(OPENTBS_SELECT_SLIDE, 1);
$pptx->VarRef["Client"] = $templateDataArray["Client"];
$pptx->Show(OPENTBS_FILE, $pptxFileNameOut);

[PPTX with merge tags_new_version.pptx](https://github.com/Skrol29/tinybutstrong/files/14385184/PPTX.with.merge.tags_new_version.pptx)

**Comment by ashifaliclientpoint** [comment]
@Skrol29 any update on this issue. Clients are waiting for fix this issue ASAP.

Thanks

**Comment by ashifaliclientpoint** [comment]
@Skrol29 Can you please check this issue.

**Comment by Skrol29** [comment]
Hi,

Sorry to be long, the support is supposed to be at https://stackoverflow.com/

In your case, the problem comes from the template : the TBS fields has been invisibly cut by the spell and grammar feature.
Simply select the TBS field, and choose _Review_, _Language_, _Set Proofing Language_, then check _Do not check spelling_.

Regards,

**Comment by ashifaliclientpoint** [comment]
Thanks for reply.
Any other solution? We can't say clients to do changes in pptx manually. They have lots have pptx. 
Is there any other way, that we can fix this by using code.

Thanks

**Comment by Skrol29** [comment]
I've just tested an enhancement for OpenTBS that seems to work :  strengthen the cleaning of MsPowerpoint XML by including a cleaning point already used for MsWord. 
It seems to solve your case.
Let me make some non-regression tests, and I will publish a new version if it's ok.

**Comment by ashifaliclientpoint** [comment]
That is great. If this issue will fix with any other version. 
Please update me when you done your testing.

Thanks

**Comment by Skrol29** [comment]
You can already test the beta, at the [OpenTBS](https://github.com/Skrol29/opentbs) repo

**Comment by Skrol29** [comment]
@ashifaliclientpoint 

[OpenTBS 1.12.1]( https://github.com/Skrol29/opentbs/releases) is released. 

Regards,
