### ISSUE TITLE
How to run the unit tests

### ISSUE THREAD

**Issue by simonschaufi** [Skrol29/tinybutstrong#8]
I see that simple unit test framework is used and not phpunit. I have no idea how to run the tests on command line. please help!

**Comment by roxblnfk** [comment]
[There](https://github.com/Skrol29/tinybutstrong/pull/6) I did support testing in console mode

**Comment by simonschaufi** [comment]
I was wondering how to get it running with the plugins as there is a die when they are not there.

**Comment by Skrol29** [comment]
> I was wondering how to get it running with the plugins as there is a die when they are not there.
The last commit fixes this problem. Plugins were includes but not used.

Sorry the SimpleTest framework is quite old ans unmaintained.
